amaranth-lang/amaranth

- nmigen/lib/cdc.py
- nmigen/test/test_lib_cdc.py
PulseSynchronizer ported from issue #47, which was ported from oMigen.
> Add PulseSynchronizer to nmigen.lib.cdc.

- nmigen/vendor/lattice_ice40.py
Thanks to #nmigen on Freenode IRC; they basically wrote this for me.
> Add support for iCE40 internal oscillators.

- nmigen/back/pysim.py
- nmigen/back/rtlil.py
- nmigen/hdl/ast.py
- nmigen/hdl/rec.py
- nmigen/hdl/xfrm.py
- nmigen/test/test_hdl_ast.py
- nmigen/test/test_hdl_xfrm.py
> make Record inherit from UserValue

- nmigen/lib/fifo.py
This is the last bit of #181 which still needs to be done before that issue can be closed.
> Implement r_rst output signal for AsyncFIFO

- nmigen/lib/fifo.py
- nmigen/test/test_lib_fifo.py
> Add r_level and w_level to all FIFOs

- nmigen/vendor/xilinx_7series.py
- nmigen/vendor/xilinx_ultrascale.py
> vendor.xilinx_{7series,ultrascale}: set BUFG* SIM_DEVICE as appropriate

- nmigen/hdl/mem.py
> hdl.mem: document ReadPort and WritePort.

- nmigen/vendor/quicklogic.py
Signed-off-by: Jan Kowalewski <jkowalewski@antmicro.com>
> vendor.quicklogic: fix syntax

- nmigen/vendor/lattice_ice40.py
> Lattice ICE40: Zero-pad CLKHF_DIV

- nmigen/vendor/intel.py
When using the default clock "cyclonev_oscillator" on Cyclone V devices, the internal oscillator will be used.
> intel: Add support for Cyclone V internal oscillator

- nmigen/vendor/quicklogic.py
Related PR: https://github.com/nmigen/nmigen-boards/pull/117
Signed-off-by: Jan Kowalewski <jkowalewski@antmicro.com>
> vendor.quicklogic: enable SoC clock configuration

- nmigen/vendor/lattice_ecp5.py
- nmigen/vendor/lattice_machxo_2_3l.py
> Remove -forceAll from ECP5 and MachXO2 Diamond build scripts

- examples/basic/ctr_en.py
- nmigen/_utils.py
- nmigen/back/rtlil.py
- nmigen/compat/genlib/roundrobin.py
- nmigen/hdl/ast.py
- nmigen/hdl/dsl.py
- nmigen/hdl/ir.py
- nmigen/hdl/rec.py
- nmigen/hdl/xfrm.py
- nmigen/lib/cdc.py
- nmigen/lib/fifo.py
- nmigen/sim/_pyclock.py
- nmigen/sim/_pyrtl.py
- nmigen/test/utils.py
- tests/compat/test_fsm.py
- tests/test_hdl_ast.py
- tests/test_hdl_cd.py
- tests/test_hdl_ir.py
- tests/test_sim.py
- tests/utils.py
Opened the nmigen codebase with a language server for the first time and saw some unused imports :)
Also found two small bugs while going through the files :)
The commit messages should speak for themselves.
If you want I can also split this into multiple PRs.
> Minor cleanup

- nmigen/rpc.py
> rpc: fix parsing of negative signed parameters

- amaranth/vendor/xilinx.py
> vendor.xilinx: support setting options on synth_design

- amaranth/back/rtlil.py
> back.rtlil: support slicing on Parts

- amaranth/vendor/intel.py
- amaranth/vendor/lattice_ecp5.py
- amaranth/vendor/lattice_ice40.py
- amaranth/vendor/quicklogic.py
- amaranth/vendor/xilinx.py
- docs/index.rst
- docs/platform.rst
- docs/platform/intel.rst
- docs/platform/lattice-ecp5.rst
- docs/platform/lattice-ice40.rst
- docs/platform/lattice-machxo-2-3l.rst
- docs/platform/quicklogic.rst
- docs/platform/xilinx.rst
This adds initial documentation of the vendor platform modules.
> docs: cover `amaranth.vendor`.

- amaranth/sim/_pyrtl.py
Hi,
some of my code recently started failing with this exception after a Python version bump:
```
Traceback (most recent call last):
[...]
File "/usr/lib/python3.10/site-packages/amaranth/hdl/xfrm.py", line 209, in on_statement
new_stmt = self.on_Assign(stmt)
File "/usr/lib/python3.10/site-packages/amaranth/sim/_pyrtl.py", line 349, in on_Assign
gen_rhs = f"({(1 << len(stmt.rhs)) - 1} & {gen_rhs_value})"
ValueError: Exceeds the limit (4300) for integer string conversion
```
Here's a small reproducer:
```python
from amaranth import Module, Signal, sim
dut = Module()
dut.d.sync += Signal(1).eq(Signal(1) << Signal(14))
sim.Simulator(dut)
```
This fails because the generated code uses a large mask value, which raises an ValueError during decimal formatting in Python versions that include a …
> sim._pyrtl: work around Python's new integer-string convertion limits

- amaranth/sim/_pyrtl.py
Current the value compiler translates ArrayProxy into if-elif trees which can cause the compiler to crash due to deep recursion (#359). This patch instead translates them into pattern matching when it is supported (Python >= 3.10) to avoid this problem.
> Translate ArrayProxy to pattern matching when supported

- amaranth/hdl/ast.py
> Add Repl() to ValueKey.

- amaranth/hdl/ast.py
- amaranth/lib/data.py
- amaranth/lib/enum.py
- tests/test_hdl_ast.py
- tests/test_hdl_dsl.py
- tests/test_lib_data.py
- tests/test_lib_enum.py
See https://github.com/amaranth-lang/rfcs/pull/9 and https://github.com/amaranth-lang/amaranth/issues/771.
> Implement RFC 9: Constant initialization for shape-castable objects

- .github/workflows/main.yaml
This was never intended to merge anything.
> CI: fix the document action for divergent branches

- amaranth/lib/data.py
- tests/test_lib_data.py
> lib.data: improve diagnostics for field access on array layout view

- amaranth/lib/data.py
- tests/test_lib_data.py
Fixes #838.
This is a potential site for a new diagnostic--I'm not sure though.
> lib.data: allow Const as value of Layout.const(...) field

- .gitignore
- pyproject.toml
It looks like https://pdm.fming.dev/ actually does what I want out of a package manager and has good runtime performance.
It also requires minimal to no modification to existing `pyproject.toml` files or workflow.
> Support PDM

- docs/contrib.rst
Should be mostly complete now.
> docs/contrib: expand the contribution guide

- .github/workflows/main.yaml
This simplifies repository management.
> CI: group all required workflows into one for the status check

- amaranth/build/run.py
Oops. (We don't have tests for this module.)
> Fix broken commit 5bc3768e

- amaranth/lib/scheduler.py
- docs/changes.rst
- tests/test_lib_scheduler.py
Tracking issue: https://github.com/amaranth-lang/amaranth/issues/874
Depends on: https://github.com/amaranth-lang/amaranth/pull/887
> Implement RFC 19: Remove `amaranth.lib.scheduler`

- amaranth/hdl/ast.py
- tests/test_hdl_ast.py
> ast: ensure `Part` offset is unsigned

- amaranth/back/rtlil.py
It was thought previously (by me) that adding a wire that does
nothing to an empty subfragment is enough to prevent it from being
treated as a blackbox. This is enough for Yosys but not Vivado.
Another workaround could probably be used that satisfies both, but
instead let's just not translate any empty subfragments.
This doesn't account for the case of the empty toplevel, but that
does not seem worth addressing.
Fixes https://github.com/amaranth-lang/amaranth/issues/899.
> back.rtlil: do not translate empty subfragments at all.

- amaranth/back/rtlil.py
- amaranth/hdl/mem.py
Introduced in https://github.com/amaranth-lang/amaranth/pull/893.
> Fix a few issues in memory lowering

- amaranth/vendor/_gowin.py
> vendor.GowinPlatform: oscillator improvements

- docs/tutorial.rst
I finally published a series of articles about how I set up things to work with Amaranth. I hope it is appropriate enough to put it here.
> [doc] tutorial : reference to my series of articles

- tests/test_lib_fifo.py
These were removed as a solution to #526.
> Eliminate uses of deprecated `Past` and `Rose` from FIFO tests

- amaranth/lib/wiring.py
- docs/changes.rst
- tests/test_lib_wiring.py
> Implement RFC 38: Component signature immutability.

- amaranth/lib/wiring.py
- docs/conf.py
- docs/stdlib.rst
- docs/stdlib/data.rst
- docs/stdlib/wiring.rst
- tests/test_lib_wiring.py
[Rendered](https://whitequark.github.io/amaranth/docs/rfc-2-document/stdlib/wiring.html)
> Document implementation of RFC 2: Interface definition library

- docs/changes.rst
This pull request will remain open for a bit in case we need to add any last minute changes.
> Release version 0.4

- docs/lang.rst
Fixes #661.
Also, add TODOs for unfinished language guide sections.
> Expand language guide to include all control flow syntax

- amaranth/hdl/ast.py
- tests/test_hdl_ast.py
> hdl.ast: suggest bit_select or word_select when indexing with Value.

- docs/_code/up_counter.py
- docs/_code/up_counter.v
- docs/start.rst
> Update "Getting started" docs page to track changes in the language

- amaranth/sim/pysim.py
See kuznia-rdzeni/coreblocks#357.
> sim: use `Value.cast` on traces.

- amaranth/sim/pysim.py
See kuznia-rdzeni/coreblocks#357.
> sim: use `Value.cast` on traces. [0.4 backport]

- amaranth/__init__.py
- amaranth/hdl/__init__.py
- amaranth/hdl/_ast.py
- amaranth/hdl/ast.py
- docs/reference.rst
- tests/test_hdl_ast.py
> Remove last traces of `Repl` per RFC 10

- amaranth/lib/wiring.py
The source location is set to the place where `In`/`Out` was created.
The source location of the instantiation is tracked but overwritten; we will need to change the internal structure storing those to be able to include both.
Fixes #1085.
> Track member source locations in `lib.wiring`

- .github/workflows/main.yaml
> CI: Update actions to Node 20

- amaranth/sim/pysim.py
> sim: prefix fields with `\`.

- amaranth/build/plat.py
Fixes typo introduced in commit 78b90fba.
> Fix toolchain environment variable check, attempt #2

- amaranth/hdl/_nir.py
Preparation for adding NIR tests using `assertRepr`, replaces current ad-hoc debug output.
> hdl._nir: implement __repr__ on NIR classes.

- amaranth/back/rtlil.py
- amaranth/build/plat.py
- amaranth/build/res.py
- amaranth/hdl/__init__.py
- amaranth/hdl/_ast.py
- amaranth/hdl/_ir.py
- amaranth/hdl/_nir.py
- amaranth/hdl/_xfrm.py
- amaranth/sim/_pyrtl.py
- amaranth/sim/pysim.py
- docs/changes.rst
- docs/guide.rst
- docs/reference.rst
- tests/test_build_res.py
- tests/test_hdl_ast.py
- tests/test_hdl_ir.py
> Implement RFC 53: Low-level I/O primitives.

- amaranth/build/run.py
> run: fix `execute_local_docker()` not properly catching ctrl-c

- .editorconfig
- amaranth/lib/crc/__init__.py
- amaranth/lib/crc/catalog.py
- docs/stdlib/crc.rst
- docs/stdlib/crc/catalog.rst
- tests/test_lib_crc.py
> Improvements for `amaranth.lib.crc` documentation and tests

- amaranth/sim/_pyrtl.py
- tests/test_sim.py
> sim: fix LRHS evaluation.

- amaranth/sim/_pyeval.py
- amaranth/sim/_pyrtl.py
- tests/test_sim.py
This will be used in an upcoming PR for VCD output.
> sim: add `eval_format` function.

- amaranth/back/rtlil.py
- amaranth/back/verilog.py
Easy fix for #1339 - let me know if you had something else in mind.
> back.verilog, back.rtlil: map path elements to str

- .github/workflows/main.yaml
- amaranth/lib/meta.py
Previously, two concurrent jobs were used, which caused a race condition. Serialize them.
> Fix schema publishing

- docs/conf.py
Otherwise GitHub emails me for each commit to main >.>
> Exempt https://amaranth-lang.org/schema/ (exact) from linkcheck

- amaranth/hdl/__init__.py
- amaranth/hdl/_dsl.py
- amaranth/hdl/_ir.py
- amaranth/hdl/_mem.py
- amaranth/lib/memory.py
- docs/stdlib/memory.rst
- tests/test_hdl_dsl.py
- tests/test_lib_memory.py
> hdl._dsl: raise an error when modifying an already-elaborated `Module`.

- amaranth/lib/io.py
- docs/conf.py
- docs/guide.rst
- docs/stdlib.rst
- docs/stdlib/io.rst
- tests/test_lib_io.py
[Rendered](https://whitequark.github.io/amaranth/docs/document-io/stdlib/io.html)
> Document I/O buffer library

- .editorconfig
- amaranth/sim/core.py
- pyproject.toml
- tests/test_sim.py
> Check type of testbench when adding one to a simulator

- amaranth/vendor/_siliconblue.py
Bug introduced in 028d5d807 via copy/paste.
cc @wanda-phi
> Unbreak SiliconBlue IO buffer instantiation

- amaranth/sim/pysim.py
This is a remnant of feature added in commit 11f7b887 and removed in commit 994fa815.
> Remove dead code in simulator

- amaranth/sim/core.py
- tests/test_sim.py
> Forbid adding stimuli to a running simulation

- amaranth/build/plat.py
- amaranth/build/res.py
> build: get list of used I/O ports from `Design`.

- amaranth/hdl/_ast.py
- tests/test_hdl_ast.py
> hdl: make `Const(enum_value)` work.

- amaranth/lib/data.py
- tests/test_lib_data.py
As a side effect, makes iterating over `ArrayLayout` views work.
> lib.data: accept negative int and slice for `ArrayLayout` indexing. [0.5 backport]

- amaranth/lib/io.py
- docs/changes.rst
- docs/stdlib/io.rst
- tests/test_lib_io.py
- tests/utils.py
See https://github.com/amaranth-lang/amaranth/pull/1448.
> Implement RFC 69 [0.5 backport]

- amaranth/hdl/_xfrm.py
- amaranth/sim/_base.py
- amaranth/sim/_pyrtl.py
- amaranth/sim/pysim.py
- tests/test_hdl_xfrm.py
- tests/test_sim.py
> sim: make driving parts of a signal from distinct modules possible.

- amaranth/hdl/_xfrm.py
- amaranth/sim/_base.py
- amaranth/sim/_pyrtl.py
- amaranth/sim/pysim.py
- tests/test_hdl_xfrm.py
- tests/test_sim.py
> sim: make driving parts of a signal from distinct modules possible. [0.5 backport]

- amaranth/hdl/_ast.py
- tests/test_sim.py
> hdl._ast: name Formatter instance uniquely. [0.5 backport]

- docs/install.rst
> Remove Arch installation instructions

- pyproject.toml
> Bump sphinxcontrib-platformpicker dependency

- amaranth/lib/data.py
- docs/changes.rst
- tests/test_lib_data.py
> lib.data: bring `Const`'s `ArrayLayout` capabilities up to par with views.

- amaranth/hdl/_dsl.py
- amaranth/hdl/_ir.py
- docs/changes.rst
- docs/guide.rst
- tests/test_back_rtlil.py
- tests/test_hdl_dsl.py
- tests/test_hdl_ir.py
> hdl: allow driving individual bits of signals from multiple modules or domains.

- .github/workflows/main.yaml
- amaranth/_toolchain/yosys.py
- amaranth/back/rtlil.py
- amaranth/build/res.py
- amaranth/hdl/_ir.py
- amaranth/hdl/_nir.py
- amaranth/lib/enum.py
- amaranth/lib/meta.py
- docs/install.rst
- pyproject.toml
This also adds the recently released Python 3.13 to CI.
Fixes #1504.
> Drop support for Python 3.8
