nmigen/hdl/cd.py
nmigen/lib/cdc.py
nmigen/test/test_lib_cdc.py
nmigen/vendor/intel.py
nmigen/vendor/xilinx_7series.py
nmigen/vendor/xilinx_spartan_3_6.py
nmigen/vendor/xilinx_ultrascale.py

Per discussion on PR #329, implement `AsyncFFSynchronizer` CDC primitive for async-set-sync-release synchronization and make ResetSynchronizer a wrapper around it if platform-specific support does not exist.

Create AsyncFFSynchronizer CDC Primitive

---

nmigen/back/pysim.py
nmigen/test/test_sim.py

It looks to me like the rtlil backend produces zero when the right-hand side of the modulus operation is zero, so that's what I did here.

back.pysim: Implement modulus operator

---

nmigen/compat/fhdl/verilog.py
nmigen/compat/sim/__init__.py
nmigen/test/compat/test_run_simulation.py

Add support for using non-compat `Elaboratable` instances with `compat.fhdl.verilog.convert` and `compat.run_simulation`
Fixes #344

Add support for using non-compat Elaboratable instances with some compat functions

---

nmigen/vendor/lattice_ecp5.py

nextpnr now supports -12k; which replaces the use of -25k and --idcode
together to build bitstreams compatible with -12F devices. Use this.
This also removes the LFE5UM-12K and its 5G counterpart; as per Dave Shah
they're currently only theoretical FPGAs.

vendor: use nextpnr -12k for -12F devices; remove theoretical devices

---

nmigen/back/verilog.py

`re.match` only matches at the beginning of the string, not each line. This change changes it to do a `re.search` with the multiline flag. I think this is primarily of use when the user has compiled yosys with verific extensions.
Example of `yosys -V` output that failed with the prior code:
```
~/s/nmigen · yosys -V
-- (c) Copyright 1999 - 2020 Verific Design Automation Inc. All rights reserved
-- Compilation time was Fri Feb 28 11:19:43 2020
-- This program will expire on Sun Jun  7 12:19:43 2020
Yosys 0.9+2406 (git sha1 cf716e1f, gcc 8.3.0-6 -Os)
```
Verilog generation is still borked. `yosys -q -` doesn't seem to stop the Verific license from being printed, so it gets captured in the subprocess stdout when nmigen grabs the output from yosys. It might be a bit more foolproof to modify …

Fix `_yosys_version()`

---

nmigen/back/verilog.py

See comments at the end of #364.

remove non-verilog code at start of output

---

nmigen/hdl/ir.py
nmigen/test/test_hdl_ir.py

The `ports` argument to the `convert` functions is a frequent hotspot of
beginner issues. Check to make sure it is either a list or a tuple, and
give an appropriately helpful error message if not.
Resolves #362 .

Check type of `ports` argument to `convert` functions.

---

nmigen/vendor/lattice_machxo2.py

As others lattice and specially ECP5, machXO2 FPGA, a .bit file may be used to direct SRAM programming instead of FLASH programming.
Advantages are:
- extends FLASH lifetime
- reduces programming time.

vendor: add bit file generation for machXO2

---

nmigen/hdl/rec.py
nmigen/test/test_hdl_rec.py
nmigen/test/test_lib_io.py

Don't save the result of Shape.cast in the Layout constructor.
This allows the original user-provided shape to be preserved,
while still checking its validity.
This fixes Enum decoder inference for Signals (#393).

hdl.rec: don't save casted shapes in Layout constructor

---

nmigen/hdl/xfrm.py
nmigen/test/test_hdl_xfrm.py

Preserve allow_reset_less when remapping ResetSignal. Closes #400

---

README.md
nmigen/vendor/lattice_machxo_2_3l.py

machXO2 and machXO3l have same primitives:
- rename file : lattice_machxo2 -> lattice_machxo_2_3l
- rename class: LatticeMachXO2Platform -> LatticeMachXO2Or3lPlatform
- LatticeMachXO2Platform is now an user-alias
- add LatticeMachXO3lPlatform user alias

vendor/lattice_machxo: suppport machXO3

---

nmigen/_yosys.py

Do not use yosys binaries with unparseable version numbers. This ensures
that nmigen always knows what version of yosys it is generating RTLIL
for.
The effect of this change is that if the version number of the system
yosys is unparsable, nmigen will attempt to fallback to the builtin
Yosys.
Issue #409.

_yosys.py: handle unparseable versions

---

CONTRIBUTING.txt
LICENSE.txt

Remove non-license explanatory text from LICENSE.txt.
Create CONTRIBUTING file with instructions and notes for contributors.
This change relates to issue #412

Update license and copyright info

---

nmigen/sim/pysim.py

Fixes #429
I tested it and it seems to work!
@whitequark You can add a regression test later if you want.

write next state to vcd instead of curr state, since state is written just prior to commit

---

docs/install.rst

Signed-off-by: Filipe Laíns <lains@archlinux.org>

docs: add install instructions for arch

---

nmigen/vendor/lattice_ecp5.py

This PR fixes #446 by adding the missing IO type.

Add SSTL135D_I/SSTL15D_I/SSTL18D_I to the list of diff io types in ECP5

---

nmigen/vendor/xilinx_7series.py
nmigen/vendor/xilinx_ultrascale.py

The parameter defaults to "ULTRASCALE", even when synthesizing for 7-series devices. This could lead to a simulation/synthesis mismatch, and causes a warning.
Fixes #438.

vendor.xilinx_{7series,ultrascale}: add SIM_DEVICE parameter

---

nmigen/hdl/mem.py

Currently if you pass a list of items which can be converted to an integer but are not integers (for example, `numpy.int64` objects), they are converted when used to initialise `Memory._array`, but a transparent read port sets its reset value to `mem.init[0]`, which is not cast.
This eventually causes VcdWriter to bomb out because it checks `isinstance(value, int)` which fails for `numpy.int64`.
This PR uses `operator.index` to cast the value to an integer, the same way it's done inside the init setter when creating `Memory._array`.
Test case:
```python
import numpy as np
import nmigen as nm
from nmigen.back import pysim
class Foo(nm.Elaboratable):
def __init__(self):
self.idx = nm.Signal(7)
self.out = nm.Signal(8)
def elaborate(self, platform):
data = np.arange(128, dtype=np.int)
mem = …
```

Cast reset value for transparent read ports to integer

---

nmigen/vendor/xilinx_7series.py
nmigen/vendor/xilinx_ultrascale.py

vendor.xilinx_{7series,ultrascale}: use BUFGCTRL rather than BUFGCE

---

nmigen/build/plat.py
nmigen/build/res.py
nmigen/test/test_build_res.py
nmigen/vendor/intel.py
nmigen/vendor/lattice_ecp5.py
nmigen/vendor/lattice_ice40.py
nmigen/vendor/lattice_machxo_2_3l.py
nmigen/vendor/xilinx_7series.py
nmigen/vendor/xilinx_spartan_3_6.py
nmigen/vendor/xilinx_ultrascale.py

When a port component is skipped, it should appear neither in the RTL nor in the constraint file. However, passing around components of differential ports explicitly makes that harder.
Fixes #456.
Supersedes #457.

build,vendor: never carry around parts of differential signals

---

nmigen/vendor/lattice_ecp5.py
nmigen/vendor/lattice_machxo_2_3l.py

Otherwise specifying a name different from "top" in build does not work.

Fix diamond impl dir

---

nmigen/vendor/lattice_machxo_2_3l.py

Might be nice to rename the FLASH svf to `{{name}}_flash.svf`, but this would be a breaking change I guess.

vendor.lattice_machxo_2_3l: add SRAM svf generation

---

nmigen/build/run.py
setup.py

Add `execute_remote_ssh` method to `BuildPlan`, and `RemoteSshBuildProducts` class to `nmigen.build.run`. Also add `paramiko` to `extras_require`.

SSH Client Support via Paramiko

---

nmigen/vendor/lattice_ecp5.py
nmigen/vendor/lattice_machxo_2_3l.py

Diamond does not provide "`diamond_env.bat`" on Windows. It is up to the user to create their own and point `NMIGEN_ENV_Diamond` to the correct location. I've added an example (with the default install directory `lscc`) of a working script to the documentation.

Add documentation for how to set up NMIGEN_ENV_Diamond on Windows.

---

nmigen/hdl/ir.py
tests/test_hdl_ir.py

48d4ee4 added the option to specify attributes using Instance arguments, but the error message wasn't updated accordingly.

hdl.ir: Update error message for Instance arguments

---

setup.py

67b957d moved the tests from `nmigen/test/` to `tests/`, and removed the `exclude=` parameter from `find_packages()` in setup.py. However, even if the new location is not inside the module tree, it is still found by `find_packages()`, resulting in a stray "tests" module on the system.

setup.py: Exclude "tests" package

---

tests/utils.py

This PR improves the internal version of FHDLTestCase by trying to get the last stack frame that is still inside the nmigen codebase when creating names for the spec file. This helps to make the FIFO test cases produce all distinct spec directories and makes the nmigen test suite thread-safe (can be run successfully with pytest-xdist)

improve spec directory name of FHDLTestCase

---

nmigen/lib/fifo.py
tests/test_lib_fifo.py

This is the split out commit with testcase as requested for #512 in IRC

Fix latency issues with AsyncFIFO

---

setup.py

I'm working on setting up a Nix shell environment, which builds nmigen from a checkout that does not contain a full .git directory. In the this scenario, setuptools_scm is installed correctly, but `parse`/`parse_git` returns `None` because there's no active git checkout.
As a fix, I check to see if `git` is falsey and, if so, return a blank version string. 
I've verified that this installs properly from nix via `fetchFromGithub`

Handle installation when not running from a full git checkout

---

nmigen/lib/cdc.py
tests/test_lib_cdc.py

wasted more time than I would like to admit due to this :)

lib.fifo.AsyncFFSynchronizer: check input and output signal width

---

nmigen/vendor/quicklogic.py

The PR introduces two general changes:
* Fixing the nomenclature of the toolchain according to the latest SymbiFlow QuickLogic toolchain package
* Adding a possibility to utilize internal SoC clock
Related PR: https://github.com/nmigen/nmigen-boards/pull/117

Quicklogic Quickfeather integration

---

nmigen/lib/fifo.py
tests/test_lib_fifo.py

This is the split out stuff from #512 that affects AsyncFIFO and not AsyncFIFOBuffered

lib.fifo: fix level on fifo full

---

nmigen/lib/fifo.py
tests/test_lib_fifo.py

This Fixes #485 as per discussion in https://freenode.irclog.whitequark.org/glasgow/2020-10-22#1603367304-1603369561

Fix {r,w}_level in AsyncFIFOBuffered

---

nmigen/vendor/xilinx_7series.py

The Zynq driver in the FPGA Manager framework on Linux expects bitstreams that
are byte swapped with respect to what the Vivado command
`write_bitstream -bin_file` produces. Thus, use the `write_cfgmem` command with
appropriate options to generate the bitstream (.bin file).
Fixes #519.

vendor.xilinx_7series: byte swap generated bitstream

---

nmigen/hdl/ast.py
tests/test_hdl_ast.py

Implement the ValueCastable type as described in #355 .

Implement ValueCastable

---

nmigen/hdl/rec.py
tests/test_hdl_rec.py

This PR migrates Record from being based on UserValue to being based on ValueCastable, clearing the way to deprecate UserValue.
Would close #528 .

Migrate Record to ValueCastable, from UserValue

---

nmigen/hdl/rec.py
tests/test_hdl_rec.py

Proxy Operator calls on Record through to Value implementation, using explicit enumeration to avoid depending on future changes to Value.
Fixes #533 .

Fix Record Operators

---

nmigen/sim/_pyrtl.py
tests/test_sim.py

Otherwise it behaves funny when it's eg. the result of operator ~.

pysim: Run mask on Mux selection operand.

---

nmigen/hdl/rec.py
tests/test_hdl_rec.py

Record lost shape() in the migration to ValueCastable. This PR restores it.

Implement shape() for Record

---

nmigen/lib/fifo.py
tests/test_lib_fifo.py

This includes a number of fixes for `{r,w}_level` in AsyncFIFOBuffered.
1. The accounting for the output register used `AsyncFFSynchronizer` instead of `FFSynchronizer`. This is wrong as we want to synchronize both edges
2. Use the proper clock domains in the tests (not really a bug in the fifo logic obviously)
3. The FFSynchronizer should have a latency of 4 to match the latency of `consume_w_bin` / `w_level`. Two cycles for the `FFSynchronizer` from the read to the write domain of `consume_w_gry`, one for the `GrayDecoder` and one for the `w_level` calculation.
4. Fix the output register accounting. If the user asserts `r_en` even if `r_rdy` is low, we get `-1` in the intermediate calculation which overflows to `1` as we have a unsigned `Signal`
Let me know if I should split this into …

AsyncFIFOBuffered {r,w}_level fixes

---

nmigen/vendor/lattice_ecp5.py

Starting with nextpnr c6401413a, nextpnr does pack *FS1P3DX into IOLOGIC cells.

Remove outdated comment in ECP5 platform

---

docs/_code/up_counter.py

nmigen/docs/_code/up_counter.py:44: DeprecationWarning: instead of nmigen.back.pysim.*, use nmigen.sim.*
from nmigen.back.pysim import Simulator

docs: Update up_counter to avoid deprecation warning

---

nmigen/vendor/lattice_ecp5.py

My design has a SDR 16-bit bidirectional I/O, and currently nmigen emits a single OFS1P3DX instance for the OE signal, and its output is used for all 16 BB instances. nextpnr then complains:
ERROR: Failed to pack flipflop 'pin_adc_0__db.U$$32' with 'syn_useioff' set into IOLOGIC.
The problem seems to be having one instance of OFS1P3DX, which yosys marks syn_useioff, but it can't be packed because it's needed in 16 places. This PR updates `lattice_ecp5.py` to generate n OFS1P3DX for the OE (well, T) signal instead, which nextpnr does then pack into IOLOGIC successfully. I've also tried this with DDR OE outputs which were also packed successfully, so I removed that comment too.
Happy to hear if you'd rather make a wider OE signal and use the normal `get_oreg` with it instead, or anything …

ECP5: Replicate OE FF for each output bit

---

nmigen/vendor/lattice_ecp5.py

This fixes a logic bug introduced in 6ce2b21e196a0f93b82748ed046098331d20b3bf.

vendor.lattice_ecp5: correctly generate OE signaling when xdr=0

---

nmigen/vendor/xilinx_7series.py

Prefix "tools" with symbiflow_ as is done for the QuickLogic Symbiflow
toolchain. Installing symbiflow gives me the tools with the preifx, so I
guess this is the correct way to move forward.
I tested this by adding `toolchain=Symbiflow` to the constructor of basys3 (not upstreamed yet) and arty_a7 platform.
~There is a slight issue, but possibly with my symbiflow env where I see:~
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/nickoe/symbiflow_install/xc7/conda/envs/xc7/share/symbiflow/prjxray-db/xc7a35tcsg324-1/tilegrid.json'
```
~There should be artix7 prefixed the chip name there. I assume this is an issue in the prjxray* or something. Possibly related to https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1947.~
Maybe @mglb wants to have a quick look at this as …

Fixup symbiflow toolchain for xilinx 7series

---

nmigen/compat/genlib/roundrobin.py

This fixes some missing imports in the code introduced in commit 20f9ab9

compat.genlib.roundrobin: fix missing imports

---

nmigen/_toolchain/__init__.py

`tool_env_var("g++")` returns `"G++"`, which is not a valid environment variable name.

_toolchain: substitute '+' with 'X' in tool_env_var().

---

nmigen/_toolchain/cxx.py

The `test_toolchain_cxx.py` tests definitely use compiler and linker set
with `_so_cxx`-suffixed parameters. After this change tests use a proper
executable instead of `c++`.

_toolchain: Properly set compiler/linker executables on Gentoo

---

nmigen/vendor/xilinx.py

This patch was proposed by whitequark originally:
https://freenode.irclog.whitequark.org/nmigen/2021-04-10#29646879
I came across an issue when instantiating a PLL inside a submodule. The generated clock constraint by nMigen would  have `/` characters in the string, which caused errors in ISE. Changing the character to `__` fixed the problem.

Change the character used for constraint hierarchy

---

nmigen/hdl/ast.py

Using sum(lst, []) to flatten a list of lists has quadratic time
complexity. Use chain.from_iterable() instead. While not strictly
necessary to improve performance, convert to map().
A test case writing out verilog for a 512k entry FIFO is 120x faster
with this applied.

Remove quadratic time complexity in Statement.cast()

---

amaranth/back/rtlil.py
amaranth/back/verilog.py
tests/utils.py

back.{rtlil,verilog}: deprecate implicit ports.

---

examples/basic/uart.py

The UART example code currently sets `rx_rdy` high when data has been received. I had assumed that setting `rx_ack` to high would clear this until data is ready again, but in the existing implementation `rx_rdy` only goes low when new data arrives. This small diff changes `rx_ack` to clear `rx_rdy` so that a user can acknowledge data after the first byte and then waits on `rx_rdy` for the next one. It also updates the simulation to verify that the right thing happens.
I suppose this could've been designed with the intent that the user strobes out a signal when `rx_rdy` goes from low to high, but I'm not sure what the use of `rx_ack` is if this was the intended design. Sorry if I'm being oblivious, but if I am, feel free to close out this diff.

Update UART Example so that acknowledging RX data sets RX ready low.

---

amaranth/sim/pysim.py
docs/changes.rst
tests/test_sim.py

sim.pysim: use "bench" as a top level root for testbench signals.

---

amaranth/back/rtlil.py

Avoiding emission of sync processes in RTLIL allows us to avoid a dependency on matching the behavior expected by Yosys, which generally expects sync processes in RTLIL to match those emitted by the output from it's own Verilog parser. This also simplifies the logic used in emitting RTLIL overall.
Combinatorial processes are still emitted however. Without these the RTLIL does not have a high-level understanding of `Switch` statements, which significantly diminishes the quality of emitted Verilog, as these are converted to `$mux` cells in Yosys, which become `?` constructs when converted back to Verilog.
Fixes #603.

back.rtlil: avoid sync process emission in RTLIL.

---

setup.py

For me also latest Jinja2 version is working fine and strict requirement of old version is conflicting with other libs using nmigen, e.g. https://github.com/lambdaconcept/lambdasoc/blob/master/setup.py

Loosen dependency on Jinja2 version

---

amaranth/back/verilog.py

Fix the strip_internal_attrs parameter to verilog.convert by passing it
down the call stack as intended.
Signed-off-by: Alyssa Rosenzweig <alyssa@rosenzweig.io>

back.verilog: Fix strip_internal_attrs

---

amaranth/sim/core.py
tests/test_sim.py

Now more in line with the documentation, which states that the process will wait ``phase`` seconds.
Ref:
https://github.com/amaranth-lang/amaranth/blob/c83b51db6daf3b73fb2406fdeecf6ef7486bb0be/amaranth/sim/core.py#L104-L106
This was not true so far.
One had to give the clock phase wait time in ps.

sim: Fix clock phase in add_clock having to be specified in ps. 

---

amaranth/build/plat.py

This allows `Platform.toolchain` to contain '+' or  '-' characters.

build.plat: use tool_env_var() in _toolchain_env_var.

---

amaranth/build/plat.py
setup.py

This PR fixes #688 by upgrading the Jinja2 dependency to minimum of major version 3, which does not have the issue with it's markupsafe dependency being  incorrect. In order to do this, update the uses of `@jinja2.contextfunction` to use the non-deprecated `@jinja2.pass_context` name instead, as this name will be removed in Jinja2 versions `>=3.1.0`.

Fix Jinja2 dependency

---

docs/changes.rst

Changelog update for new `debug_verilog` override

---

amaranth/vendor/lattice_machxo_2_3l.py

This PR adds support for the internal high-speed oscillator on MachXO2/XO3L devices, called OSCH. Migen had support for the oscillator, but nMigen doesn't have it yet.
It essentially replicates the changes that https://github.com/nmigen/nmigen/pull/530 made on Intel Cyclone V devices and https://github.com/nmigen/nmigen/pull/338 on the iCE40, with the difference that MachXO2/XO3 devices have a configurable frequency and a list of allowed freqs, as opposed to the Cyclone V which has a fixed frequency with a maximum of 100MHz, and the iCE40 which uses a fixed 48MHz oscillator and a divider.
This PR is accompanied by (and would allow) PR https://github.com/nmigen/nmigen-boards/pull/136 in nmigen-boards, which changes the TinyFPGAAX2Platform to use the internal clock (at 2.08 MHz) by default, …

Lattice: Add support for MachXO2/XO3L internal oscillator

---

amaranth/_toolchain/cxx.py

Starting with setuptools 64.0.2, the monkeypatching process performed as part of its bootstrap no longer imports distutils.ccompiler, causing an AttributeError.

_toolchain.cxx: fix use of distutils.ccompiler on newer setuptools.

---

.github/workflows/main.yaml

Note that CI will still fail without #722.

CI: change Python 3.11-dev to 3.11.

---

amaranth/lib/coding.py

While developing a prototype for #704 at 052647445772cfe83767b0c55dd47c196763ac82, I discovered that bits of `Graydecoder.o` are combinationally dependent on each other. When each bit is thought of as an individual signal, this is no problem, but a comb loop detection pass would be slowed down by that assumption. Regardless of if it's within the scope of the language's "no *indirect* comb loops" policy, it is easily rewritable to never have assignments that have the output signal both on the left and righ-hand sides. That is what this PR contains. All tests pass, including the formal check of gray encoding reversibility, proving correctness of this PR.

lib.coding: remove GrayDecoder comb loop for consistency

---

amaranth/vendor/xilinx.py

The symbiflow tools in f4pga have changed the required arguments.
This PR fixes the xilinx toolchain (at least for Arty A35).

fix xilinx toolchain scripts for f4pga.

---

amaranth/hdl/ast.py
docs/lang.rst
tests/test_hdl_ast.py

Example code that can make use of such changes:
```py
class Something(IntEnum):
A = 0b1000
B = 0b0000
...
class Component(Elaboratable):
def elaborate(self, platform):
m = Module()
with m.Switch(...):
with m.Case(Cat(Something.A, Something.B)):
...
```
The first commit is more important to me than the second one (you can always work it around using `Case(Cat(...)._as_const())`), but they are pretty much independent, so if it is desirable to only merge one of them, you can do it.

hdl.ast: allow IntEnum/IntFlag in Cat.

---

amaranth/vendor/xilinx.py

Adds support for parts used in Digilent CMOD boards.

vendor.xilinx: Add support for more parts when using Symbiflow.

---

amaranth/back/rtlil.py
amaranth/hdl/ast.py
amaranth/hdl/xfrm.py

This PR implements explicit naming of properties (Assert/Assume/Cover) as asked in #744. The name is specified through the use of a new optional parameter "name".
With the following code example:
```python
from amaranth import *
from amaranth.asserts import *
from amaranth.back import rtlil
m = Module()
a = Signal()
m.d.sync += Assert(a != 0, name="foobar")
print(rtlil.convert(m, ports=(a,)))
```
The `$assert` cell picks up the proper name:
```
[...]
cell $assert \foobar
connect \A $assert$check
connect \EN $assert$en
end
[...]
```
Fixes #744.

Add support for explicit names in properties

---

amaranth/build/plat.py

This was broken in 097da99.
Related to #727

build.plat: fix strings as build option overrides.

---

amaranth/build/run.py

build.run: Handle UTF-8 encoding errors in SSH output gracefully

---

docs/lang.rst

I had this confusion while reading the doc.
Someone else also likely had, unless there was a change at some point:
https://github.com/bl0x/learn-fpga-amaranth/blob/main/06_alu/soc.py#L111

docs: disambiguate Cat(a, b, ...) support for more than 2 arguments

---

amaranth/hdl/ast.py
tests/test_hdl_ast.py

The `__init_subclass__` method fires on class definition rather than use. It also has the bonus impact that no `__new__` method is defined, so the classes can be correctly detected as mix-in classes by modules such as enum.

hdl.ast: Test *Castable subclasses on definition.

---

.github/workflows/main.yaml

Docs are now uploaded as an artifact (zip archive you can download from the Actions tab), and in forks, they are also pushed to the gh-pages branch and can be previewed that way.

Improve handling of documentation on CI

---

docs/stdlib/data.rst

Found while working on amaranth/rfcs#15. The new code is also robust in the face of RFC 15 itself (the value returned by Signal will change but that will save work for the programmer).

lib.data: fix incorrect and very misleading example in documentation

---

amaranth/build/plat.py

Mixed-case variables are allowed since af7c1144, but '-' or '+' must be replaced to avoid invalid names (e.g. "$AMARANTH_ENV_oss-cad-suite").
See also #729.

build.plat: replace -+ characters in _all_toolchain_env_vars.

---

amaranth/hdl/ast.py
amaranth/lib/data.py
docs/stdlib/data.rst
tests/test_hdl_ast.py
tests/test_lib_data.py

See amaranth-lang/rfcs#15 and #784.
Note that this RFC breaks the existing syntax for initializing a view with a new signal. Instances of `View(layout)` *must* be changed to `Signal(layout)`.

Implement RFC 15: Lifting shape-castable objects

---

amaranth/lib/data.py
tests/test_lib_data.py

This is actually an existing correctness requirement (for the similar reasons that ValueCastable.as_value() must always return the same value every time) that for some reason wasn't respected.

lib.data: make all layouts immutable

---

amaranth/tracer.py
tests/test_tracer.py

This fixes the following issues:
- on Python 3.10 and earlier, storing to free variables is now handled correctly
- on Python 3.11, `_varname_from_oparg` is now used, fixing problems with cell variables that are also arguments
- on all supported versions, EXTENDED_ARG is now parsed, ensuring proper handling for long functions
Fixes #792.

tracer: fix STORE_DEREF handling, add EXTENDED_ARG support.

---

pyproject.toml

The only breaking change in 0.4 is dropping support for Python 3.6, which Amaranth has already dropped. It also adds official support for 3.10 and 3.11.
https://github.com/westerndigitalcorporation/pyvcd/blob/3ad7340072791e695e32cfb51135b751a8ddab41/CHANGELOG.rst

Allow pyvcd 0.4

---

amaranth/hdl/ast.py
tests/test_hdl_ast.py

hdl.ast: fix signed `Const` normalization.

---

amaranth/hdl/ast.py
tests/test_hdl_ast.py

hdl.ast: guard `rotate_*` against 0-width values.

---

amaranth/hdl/ast.py
tests/test_hdl_ast.py

hdl.ast: fix range handling in `Shape.cast`.

---

amaranth/hdl/ast.py
tests/test_hdl_ast.py

hdl.ast: fix shape for subtraction.

---

amaranth/back/rtlil.py
amaranth/compat/fhdl/structure.py
amaranth/hdl/ast.py
amaranth/hdl/mem.py
amaranth/hdl/xfrm.py
amaranth/sim/_pyrtl.py
amaranth/vendor/intel.py
amaranth/vendor/lattice_ecp5.py
docs/changes.rst
docs/lang.rst
tests/test_hdl_ast.py
tests/test_hdl_xfrm.py
tests/test_sim.py

Implements [RFC 10](https://amaranth-lang.org/rfcs/0010-move-repl-to-value.html); fixes #770.
* I've marked `Repl` as for removal in 0.5 with a comment, per the changelog text:
> While code that uses the features listed as deprecated below will work in Amaranth 0.4, they will be removed in the next version.
* I've left the "iffy cast" warnings in for the `Repl` wrapper.
* The regression tests for [#325](https://github.com/amaranth-lang/amaranth/issues/325) ([diff](https://github.com/amaranth-lang/amaranth/commit/ec7aee62eae4500b4840ca10003ad0a457cfb9dd#diff-35a2d4c45dcee18d4da90988d687a4eb159d749e8bcc01ae35b9ec7779901332)) now reduce to the same AST, so I removed the replicate one, as they no longer test different paths.

Implement RFC 10: Move `Repl` to `Value.replicate`

---

amaranth/sim/_pyrtl.py
tests/test_sim.py

Amaranth bitwise negation `~` compiles to Python bitwise negation `~` in simulation; the same holds for comparison operators such as `==`. Thus an expression such as `~(a == b)` in simulation will compile to Python that takes the bitwise negation of the comparison result, which will be an actual bool.
On 3.12, the result is a `DeprecationWarning` emitted only at simulation run-time.
When negating in simulation, coerce the value to an int. `mask` is sufficient as we do no further arithmetic here.

sim._pyrtl: py3.12+: convert to int before bitwise negating.

---

amaranth/sim/_pyrtl.py
tests/test_sim.py

Addresses the bug surfaced in https://github.com/amaranth-lang/amaranth/pull/826#issuecomment-1603634393.
I read through the remaining value compiler branches (and poked at a few things to see if I could break them), but I believe it's all OK from here.

sim._pyrtl: mask bitwise binary operands.

---

amaranth/sim/_pyrtl.py
tests/test_sim.py

Python pre-3.9 can't handle parentheses nested this deeply.
* https://github.com/amaranth-lang/amaranth/pull/681 -- motivating example.
* https://github.com/amaranth-lang/amaranth/pull/827 -- what added enough extra parentheses to make this only break now.
* https://peps.python.org/pep-0617/ -- new parser as of 3.9.

sim._pyrtl: don't blow parser stack on older Pythons.

---

amaranth/lib/crc/__init__.py
amaranth/lib/crc/catalog.py
docs/changes.rst
docs/stdlib.rst
docs/stdlib/crc.rst
docs/stdlib/crc/catalog.rst
tests/test_lib_crc.py

This PR adds a CRC generator to the stdlib. It supports the full set of Williams/Rocksoft model parameters, which in practice means it should be able to generate and validate pretty much every commonly used CRC directly, and significantly that includes all the ones in the [reveng catalogue](https://reveng.sourceforge.io/crc-catalogue/) and [crcmod predefined list](http://crcmod.sourceforge.net/crcmod.predefined.html).
It's configurable for arbitrary input word widths with a constant single-cycle latency, so can be used to generate a classic bit-at-a-time shift-register CRC, or update wider words in parallel. It doesn't support masking the input words, which might limit its use in very wide masked data paths, though I expect that could be added later in a backwards-compatible way if …

Add CRC generator

---

amaranth/lib/enum.py

There's an actual `py_enum.member` (which we briefly overwrite our loop index with (!)).  We delete our `member`, but it's still in the `__all__` that came from `py_enum`, so `import *` fails.

lib.enum: allow `import * from amaranth.lib.enum`.

---

amaranth/lib/data.py

Found during #830 simplification pass; copy-paste leftover from similar sites that repeatedly `.as_shape()` to unwrap.

lib.data: remove unnecessary loop.

---

amaranth/lib/io.py

The main purpose of this change is migrating glasgow from the compat `TSTriple` (which allows 0 width) to `Pin`.  This sort of change would normally require a RFC, but `Pin` is already slated for removal/replacement, so that was deemed to be unnecessary.

lib.io: allow 0-width `Pin`

---

amaranth/lib/enum.py
tests/test_lib_enum.py

Fixes the error noted in https://github.com/amaranth-lang/amaranth/pull/830#issuecomment-1613690529 where empty Python `Enum`s are shape-castable to `unsigned(0)`.
~~We move the member check from the Amaranth `Enum` implicit shape-cast into the Python `Enum` shape-cast, which the former backs onto.~~
Allows empty Amaranth `Enum`s to shape-cast to `unsigned(0)`, like Python `Enum`s, per https://github.com/amaranth-lang/amaranth/pull/832#issuecomment-1617639806.

lib.enum: allow empty enums.

---

amaranth/vendor/xilinx.py

They don't allow use of URAM288s, have the transceivers capped to 16.3 Gb/s but otherwise are simply smaller versions of Kintex US+. I don't believe any other changes are needed.
XCAU20P, XCAU25P are XCKU5P die with different device ID and software limitations
XCAU7P-15P are new parts

recognize Artix Ultrascale+ part numbers

---

amaranth/lib/data.py
tests/test_lib_data.py

lib.data: fix `Layout.const` masking for signed fields.

---

amaranth/_unused.py
amaranth/hdl/ir.py

Using `sys.excepthook` to silence the must-use warning has some false negatives: applications may catch the exception and then quit normally, e.g. becaue the error is well known and does not require a traceback to be shown (which would be noisy). The current implementation prints even more noise in that case.
In addition to the existing heuristic, silence the warning if *nothing* has been elaborated, which is almost always a reliable sign. It doesn't work if multiple designs are independently created in the application and some of them are dropped without being used, but this is unavoidable as it is not distinguishable from the mistake this warning is attempting to prevent.
Fixes #848.

hdl.ir: use additional heuristic for silencing warning

---

amaranth/build/run.py
docs/changes.rst

Build scripts are explicitly intended to have overrides that are done through the use of environment variables, and right now this would require a very awkward `run_script=False` invocation followed by copying a bit of code out of the Amaranth codebase, which is clearly suboptimal.

build.run: add `env=` argument to `BuildPlan.execute_local()`

---

amaranth/build/run.py

If it adds to the environment then it ultimately creates the same kind of problem it was intended to solve--a need to reproduce the calls to `subprocess` in the code outside. It's not that hard to merge two dicts, plus much of the time enough you can get by with having just `PATH` and `AMARANTH_ENV_*` (if even that).
If an override is wanted it can be done easily enough with:
.execute_local(env={**os.environ, "VAR": "VALUE"})

build.run: make `BuildPlan.execute_local(env=)` override environment

---

amaranth/vendor/gowin.py
docs/changes.rst
docs/platform.rst
docs/platform/gowin.rst

Supported devices: gw1n 9c / tang nano 9k

Initial support for gowin vendor via proprietary and apicula toolchain.

---

amaranth/vendor/gowin.py

vendor.gowin: unbreak `dir="o"` pins with `xdr=2`

---

docs/contrib.rst

docs/contrib: fix typo

---

amaranth/build/run.py

This makes the build impure and also causes the contents of a file outside of the build directory to be overwritten.
The check in `BuildPlan.execute_local` is also expanded to cover the possibility of an absolute path sneaking through.

build.run: prohibit absolute paths in `BuildPlan.add_file`

---

amaranth/hdl/ast.py
amaranth/lib/data.py
docs/changes.rst
tests/test_hdl_ast.py
tests/test_lib_data.py

Implement RFC 22: Add `ValueCastable.shape()`

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

lib.wiring: fix equality of `FlippedSignature` with other object

---

amaranth/vendor/gowin.py
amaranth/vendor/intel.py
amaranth/vendor/lattice_ecp5.py
amaranth/vendor/lattice_ice40.py
amaranth/vendor/lattice_machxo_2_3l.py
amaranth/vendor/quicklogic.py
amaranth/vendor/xilinx.py

This broke code that did e.g.
from amaranth.vendor.xilinx import *
which is common in amaranth-boards.

vendor/*: add missing `__all__`

---

amaranth/back/rtlil.py
amaranth/compat/fhdl/specials.py
amaranth/hdl/ir.py
amaranth/hdl/mem.py
amaranth/hdl/xfrm.py
docs/changes.rst
tests/test_hdl_ir.py
tests/test_hdl_mem.py
tests/test_hdl_xfrm.py
tests/test_sim.py

The design decision of using split memory ports in the internal representation (copied from Yosys) was misguided and caused no end of misery. Remove any uses of `$memrd`/`$memwr` and lower memories directly to a combined memory cell, currently the RTLIL one.

hdl.mem: lower `Memory` directly to `$mem_v2` RTLIL cell

---

amaranth/hdl/ast.py
docs/lang.rst
tests/test_hdl_ast.py

hdl: disallow `signed(0)` values with unclear semantics

---

amaranth/back/rtlil.py
amaranth/back/verilog.py
amaranth/lib/wiring.py
tests/test_lib_wiring.py

Fixes #883.
Depends on https://github.com/amaranth-lang/rfcs/pull/25.

back.{verilog,rtlil}: in convert(), accept a Component without ports

---

amaranth/build/res.py
amaranth/hdl/_rec.py
amaranth/lib/io.py
tests/test_build_res.py

Tracking #879.
The directions of signals in `Pin` make it convenient to use a pin signature in a component, such as in:
```python
class LEDDriver(Component):
pins: Out(Signature({"o": Out(1)}))
led_driver = LEDDriver()
connect(led_driver.pins, platform.request("led"))
````
The `platform.request` call, correspondingly, returns a flipped `Pin` object.

lib.io: make `Pin` an interface object

---

amaranth/back/rtlil.py

The attribute sees essentially no use and the information is much better served by putting it in the module name. In addition this means that the entire tree can be renamed simply by renaming the top module.
Tools like GTKWave show the names of the instances, not the modules, so they are not affected by the longer names.

back.rtlil: put hierarchy in module name instead of an attribute

---

amaranth/vendor/_lattice_ice40.py
docs/changes.rst

Add an icepack_opts override in case the user wants to pass  extra options to icepack as part of the build process. For example can be used to pass the "-s" option to disable putting the SPI flash to sleep after the FPGA is configured.

vendor._lattice_ice40: add an icepack_opts override

---

amaranth/hdl/ast.py
tests/test_hdl_ast.py

The code to accept const-castable expressions was previously added in 0c4fda92fecb0f6b1a3dce8960f8d13459c7eef1, but it was untested and had a few bugs.
Fixes #911.

ast: fix const-castable expression handling in `Signal(reset=)`.

---

amaranth/hdl/ir.py

This was introduced in commit 44711b7d, and was never used within Amaranth itself. While technically a breaking change I think this will not cause enough breakage to warrant a deprecation cycle (nor can we make this a deprecation this without a lot of work).

Elaboratable does not need ABCMeta as its metaclass

---

amaranth/lib/wiring.py

While the capability of providing signatures for components that are not parametric is useful, most Amaranth gateware is heavily parameterized, and the capability is not worth making most subclasses Liskov-incompatible with the base class (where the derived class would not provide `signature` as a class method anymore).

lib.wiring: Component.signature should not be a class method

---

amaranth/hdl/mem.py
tests/test_sim.py

hdl.mem: fix transparent read handling for simple write ports.

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

On Python <3.10, classes without annotations do not get an `__annotations__` member at all, so the `getattr` on a subclass falls back to the parent class `__annotations__`, attempting to create signature members twice.  Fix that by looking at the `__dict__` instead.

lib.wiring: fix `Component.signature` on subclasses without annotations.

---

amaranth/lib/data.py
tests/test_lib_data.py

`Layout.const()` is updated as per amaranth-lang/rfcs#29.

lib.data: return `View` from `.const()`

---

amaranth/lib/io.py

I expected `Pin.o` and `Pin.oe` to have identical flow.

lib.io: `Pin.oe` should have `Flow.Out`

---

amaranth/lib/enum.py
tests/test_lib_enum.py

lib.enum: allow using functional syntax for enum creation.

---

amaranth/lib/fifo.py
docs/changes.rst
tests/test_lib_fifo.py

Implement RFC 20: Deprecate non-FWFT FIFOs.

---

.github/workflows/main.yaml

While this fails a normal required status check, the merge group will succeed even if a required status check is skipped.

CI: adjust the `required` job to never be skipped

---

amaranth/back/verilog.py
pyproject.toml

Fixes #931.
Requires https://github.com/amaranth-lang/amaranth-yosys/actions/runs/6945417785 to complete.

back.verilog: require Yosys >=0.35

---

amaranth/hdl/ir.py
amaranth/sim/_pyrtl.py
amaranth/sim/pysim.py
tests/test_hdl_ir.py

At the moment there are two issues with assignment of names in pysim:
1. Names are not deduplicated. It is possible (and frequent) for names to be included twice in VCD output.
2. Names are different compared to what is emitted in RTLIL, Verilog, or CXXRTL output.
This PR fixes issue (1), and issue (2) will be fixed by the new IR.

Move PySim name extraction functionality to Fragment and improve it

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

Although `@property` is the most common case, any descriptors are now properly supported.
The special casing of methods goes away as they work by having functions implement the descriptor protocol. (`__get__` has some special behavior to make this possible.)

Expand flipped object forwarding in `lib.wiring` to respect `@property` and `del`

---

amaranth/lib/io.py
tests/test_build_res.py

This was broken by #915, when platform started handing out `FlippedInterface` versions of `Pin`.

lib.io: fix Pin.eq to work when FlippedInterface is involved.

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

Fixes #935.
This behavior isn't clearly specified one way or another in the RFC, and the implementation in the PR feels more appropriate to me.

lib.wiring: in `is_compliant(sig, obj)`, check that `obj` is an interface object with that signature

---

amaranth/back/rtlil.py
amaranth/hdl/_repr.py
amaranth/hdl/ast.py
amaranth/lib/data.py
amaranth/lib/enum.py
amaranth/sim/pysim.py

See #790.
This PR adds an entirely private API for describing formatting of values that is used in the standard library, in departure from our standing policy of not using private APIs in the standard library.
This is a temporary measure intended to get the version 0.4 released faster, as it has been years in the making. It is expected that this API will be made public in the version 0.5 after going through the usual RFC process.
This PR only adds VCD lines for fields defined in `lib.data.Layout` when using `sim.pysim`. The emitted RTLIL and Verilog remain the same. It is expected that when `sim.cxxsim` lands, RTLIL/Verilog output will include aliases for layout fields as well.
The value representation API also handles formatting of enumerations, with no changes visible to the designer. …

Add support for dumping structure fields in VCD

---

amaranth/lib/data.py
tests/test_lib_data.py

This is an alternative of #964 for discussion purposes.

lib.data: implement equality for `View`, reject all other operators.

---

amaranth/sim/pysim.py

Rather than requiring each additional requested trace to be a signal, all of the signals in the provided value are added to the GTKW file and to the VCD file if they are not already there. This improves usability for `lib.data` as struct fields can now be added to traces.

Admit non-signals in `Simulator.write_vcd(traces=...)`

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

Implement RFC 34: Rename `amaranth.lib.wiring.Interface` to `PureInterface`.

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

Fix `__repr__` for PureInterface subclasses

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

lib.wiring: use tracer to obtain default Signature path and src_loc.

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

Their `str()` and `repr()` values are already that; and the 0 and 1 don't make sense. The RFC leaves it unspecified.

Make values of `wiring.In` and `wiring.Out` be strings "In" and "Out"

---

amaranth/lib/wiring.py
docs/changes.rst
tests/test_lib_wiring.py

Implement RFC 37: Make ``Signature`` immutable.

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

The order in which members of a `Signature` are defined can communicate developer intent, which is useful to preserve when generating documentation.

lib.wiring: preserve insertion order in `SignatureMembers.__iter__`.

---

amaranth/lib/fifo.py
docs/changes.rst
docs/stdlib/fifo.rst
tests/test_lib_fifo.py

Fixes #875.
Note: this depends on #840 and will fail tests without it.

(Merge after 0.4 is released) Remove non-FWFT FIFOs

---

amaranth/hdl/ast.py
docs/changes.rst
docs/lang.rst
tests/test_hdl_ast.py

hdl.ast: make `Slice` const-castable.

---

amaranth/build/run.py
docs/changes.rst

One usecase for this is using amaranth with vivado on MacOs.

build.run: add BuildPlan.execute_docker()

---

docs/_static/custom.css

The side nav-bar tweaks should only be valid when the side nav bar is present. It is only present on displays wider than 769px.

docs: fix nav-bar on mobile

---

amaranth/hdl/dsl.py

hdl.dsl: fix handling of redundant `Case` branches.

---

amaranth/hdl/ast.py

This ensures things like `Const(1.5)` raise an error.

hdl.ast: use `operator.index` instead of `int`.

---

amaranth/_utils.py
amaranth/back/rtlil.py
amaranth/hdl/ast.py
amaranth/hdl/dsl.py
amaranth/lib/fifo.py
amaranth/utils.py
docs/changes.rst
tests/test_utils.py

Reexports of `amaranth.utils` functions are removed from `amaranth._utils` to avoid a circular import issue (for `deprecated`). Since this is a private module, this should not be a problem.

Implement RFC 17: Remove `log2_int`.

---

amaranth/back/rtlil.py
amaranth/hdl/ir.py
amaranth/hdl/mem.py
amaranth/hdl/xfrm.py

Extracted from the new IR branch and expanded a bit, as it is useful on its own.

hdl.ir: collect source location for `Instance`.

---

amaranth/back/rtlil.py
amaranth/hdl/mem.py
amaranth/hdl/xfrm.py
tests/test_hdl_xfrm.py

Extracted from the new IR branch as a standalone PR.
Fixes #611.

hdl.mem: Switch to first-class IR representation for memories.

---

amaranth/back/verilog.py
pyproject.toml

Fixes #1049.
This can be merged once https://github.com/YosysHQ/yosys/pull/4150 is in and the version range is final.

back.verilog: forbid Yosys version range with dangling else bug.

---

amaranth/hdl/ast.py
docs/changes.rst
tests/test_hdl_ast.py

hdl.ast: change warning on out-of-range reset to an error, improve it.

---

amaranth/hdl/dsl.py
tests/test_hdl_dsl.py

Warn if a case is defined after a default case

---

amaranth/__init__.py
amaranth/hdl/_ast.py
docs/guide.rst
docs/index.rst
docs/intro.rst
docs/reference.rst
docs/start.rst
docs/stdlib.rst
tests/test_hdl_ast.py

[Rendered](https://whitequark.github.io/amaranth/docs/reference/reference.html)

Start writing reference documentation for the language

---

amaranth/hdl/ast.py
amaranth/hdl/cd.py
amaranth/hdl/dsl.py
amaranth/hdl/ir.py
amaranth/hdl/mem.py
amaranth/hdl/xfrm.py

These were originally planned to be committed as a part of 5dd1223c, but were lost during rebasing.

Add missing compatibility shims in `amaranth.hdl`

---

amaranth/back/rtlil.py

Amaranth doesn't emit sync rules for a while since these are private for the Yosys Verilog frontend.

back.rtlil: remove _SyncBuilder. NFC

---

amaranth/lib/fifo.py

This makes the generated netlist very slightly nicer.

lib.fifo: add `Memory` as submodules instead of its ports. [NFC]

---

amaranth/back/rtlil.py
amaranth/hdl/_ast.py
amaranth/hdl/_dsl.py
amaranth/hdl/_xfrm.py
amaranth/sim/_pyrtl.py

This subclassing is unnecessary and makes downstream code more complex. In the new IR, they are unified into cells with the same name anyway. Even before that, this change simplifies things.

Remove subclassing of `AnyValue` and `Property`

---

amaranth/hdl/_ast.py
docs/changes.rst
tests/test_hdl_ast.py

Implement RFC 46: Change `Shape.cast(range(1))` to `unsigned(0)`.

---

amaranth/build/plat.py
amaranth/build/run.py
amaranth/vendor/_lattice_machxo_2_3l.py

Some of these were forgotten previously.
Also, fix a comment in `BuildPlan.execute_local` to use the correct version.

Remove features deprecated in past releases

---

amaranth/vendor/_xilinx.py

This closes #721 by implementing `get_async_ff_sync()` using FDPE primitives to obtain exactly the netlist that we want. This consits of a chain of `N` FPDEs (by default `N = 2`) with all their PRE pins connected to the reset for a positive edge `reset` or to the `~reset` for a negative edge reset. The D pin of the first FDPE in the chain is connected to GND.
To make timing analysis work correctly, two new attributes are introduced: `amaranth.vivado.false_path_pre` and
`amaranth.vivado.max_delay_pre`. These work similarly to `amaranth.vivado.false_path` and `amaranth.vivado.max_delay`, but affect only the PRE pin, which is what is needed for this synchronizer. The TCL has been modified to generate constraints using these attributes, and there are comments explaining how to use the …

xilinx: use FDPE instances to implement get_async_ff_sync()

---

amaranth/hdl/_ast.py
tests/test_hdl_ast.py

hdl.ast: make it impossible to construct `*Castable` instances.

---

amaranth/back/rtlil.py
amaranth/hdl/_ast.py
amaranth/hdl/_dsl.py
amaranth/hdl/_ir.py
amaranth/hdl/_mem.py
amaranth/hdl/_xfrm.py
amaranth/sim/_pyrtl.py
tests/test_hdl_dsl.py
tests/test_hdl_ir.py
tests/test_hdl_xfrm.py
tests/test_lib_wiring.py
tests/test_sim.py

Fixes #1079.
This does not remove `Fragment.drivers` — that will be done when the new IR lands and the remaining uses in `hdl._ir` can be killed.
This also does not remove the special signals inside `Property` — they are still used within RTLIL backend, and likewise will be removed when the new IR lands.

hdl.ir: associate statements with domains.

---

amaranth/back/rtlil.py
amaranth/hdl/_dsl.py
amaranth/hdl/_ir.py
amaranth/hdl/_mem.py
amaranth/hdl/_xfrm.py
amaranth/sim/_pyrtl.py
tests/test_hdl_dsl.py
tests/test_hdl_ir.py
tests/test_hdl_xfrm.py
tests/test_lib_wiring.py
tests/test_sim.py

hdl: consistently use "comb" for combinatorial domain.

---

amaranth/hdl/_ast.py
amaranth/hdl/ast.py

These aren't used internally anymore and haven't been used in any code published on GitHub, so they are simply removed rather than deprecated.

Remove `ValueKey`, `ValueDict`, `ValueSet`

---

amaranth/hdl/_ast.py
docs/guide.rst
docs/reference.rst
tests/test_hdl_ast.py

Except `Value.matches`, `Value.__getitem__`, and `Value.implies`.

Add reference documentation for `Value`, `ValueCastable`, `ValueLike`

---

amaranth/back/verilog.py
pyproject.toml

This avoids the Verilog backend bug in Yosys 0.37.

Require Yosys 0.38 [0.4 backport]

---

amaranth/hdl/_ast.py
amaranth/hdl/_rec.py
amaranth/lib/data.py
amaranth/lib/enum.py
tests/test_hdl_ast.py
tests/test_lib_wiring.py
tests/test_sim.py

hdl._ast: deprecate `ValueCastable.lowermethod`.

---

amaranth/back/verilog.py
pyproject.toml

This avoids the awkward requirement due to the bug in Yosys 0.37, and will soon be required anyway once the `$check` cell is emitted.

Require Yosys 0.38

---

amaranth/vendor/_intel.py

vendor._intel: use `dff` instead of `$dff`.

---

amaranth/hdl/_ast.py
amaranth/lib/wiring.py
docs/conf.py
docs/guide.rst
docs/reference.rst
docs/stdlib/wiring.rst

I originally picked `:pc:` as it is short for "python code", but it is obscure and `:py:` is not taken, so a much more obvious role can be used instead. Also, we all typo `:pc:` as `:py:` all the time anyway.

docs: use `:py:` role for inline Python code, not `:pc:`. NFC

---

amaranth/hdl/_ast.py
tests/test_hdl_ast.py

This comes up in `AssignmentLegalizer`-produced `Switch`es for `ArrayProxy`.

hdl._ast: fix using 0-width `Switch` with integer keys.

---

amaranth/hdl/ast.py
tests/test_hdl_ast.py

This comes up in `AssignmentLegalizer`-produced `Switch`es for `ArrayProxy`.

hdl._ast: fix using 0-width `Switch` with integer keys. [0.4 backport]

---

amaranth/hdl/dsl.py
tests/test_hdl_dsl.py

hdl._dsl: fix using 0-width `Switch` with integer keys. [0.4 backport]

---

amaranth/hdl/_dsl.py
tests/test_hdl_dsl.py

Fixes #1133.
Depends on #1134.

hdl._dsl: fix using 0-width `Switch` with integer keys.

---

.github/workflows/main.yaml
amaranth/lib/crc/__init__.py
docs/.gitignore
docs/conf.py
docs/contrib.rst
docs/install.rst
docs/intro.rst
pyproject.toml

Fix link rot in docs

---

amaranth/hdl/_ast.py
docs/changes.rst
tests/test_hdl_ast.py

hdl._ast: make `Shape` immutable and hashable.

---

amaranth/utils.py

No deprecation or other changes — just transplanting the functions raw from current main for minimal disruption.

utils: backport `ceil_log2` and `exact_log2`. [0.4 backport]

---

amaranth/back/rtlil.py
amaranth/hdl/_dsl.py
amaranth/hdl/_ir.py
amaranth/hdl/_mem.py
amaranth/hdl/_nir.py
amaranth/hdl/_xfrm.py
amaranth/sim/_pyrtl.py
tests/test_hdl_dsl.py
tests/test_hdl_ir.py
tests/test_hdl_xfrm.py

hdl, back.rtlil: track and emit module locations.

---

amaranth/hdl/__init__.py
amaranth/hdl/_ir.py
amaranth/hdl/_mem.py
amaranth/hdl/_xfrm.py
amaranth/lib/fifo.py
amaranth/lib/memory.py
amaranth/sim/_pyrtl.py
amaranth/sim/pysim.py
docs/changes.rst
docs/stdlib.rst
examples/basic/mem.py
tests/test_hdl_mem.py
tests/test_hdl_xfrm.py
tests/test_lib_fifo.py
tests/test_lib_memory.py
tests/test_sim.py

Implement RFC 45: Move `hdl.Memory` to `lib.Memory`.

---

amaranth/lib/enum.py
tests/test_lib_enum.py

Use `_EnumDict._member_names` to determine which members to consider. This way we don't need to redo sunder/dunder checks, and non-members are correctly excluded.
This is a defacto public API, given it remains usable from py3.8 until py3.12 inclusive.  (`_member_names` changes from a list to a keys-only dict for performance reasons in py3.11, but they iterate the same.) In current Python main (i.e. what will most likely be 3.13), a `member_names` property is added which returns those keys.

lib.enum: honor enum.nonmember.

---

amaranth/hdl/_ir.py
tests/test_hdl_ir.py

This isn't expected to result in a significant increase in memory use, so for now it's enabled by default. Elaboration chains where it is not desired to preserve origins can delete the `_origins` attribute from the fragment and nothing will be stored.
The interface `Fragment._origins` remains private, as is the rest of the `Fragment` interface (including itself), but it enables certain codebases that currently use a much more invasive technique to rely on reading a single private field.
If this interface proves to be sufficient and useful, it will graduate in a largely unmodified form into a stable interface on `Fragment`'s successor.

Remember origins of a fragment during elaboration

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

Commit message:
> If a `connect()` call results in no connections being made, and it's because there were no outputs specified at all, issue an error.
---
(I've read the RFCs and git logs reasonably carefully but I'm basically assuming I've missed something/a decision made since. Apologies if so!)
[RFC 2 § Interface connection](https://amaranth-lang.org/rfcs/0002-interfaces.html#interface-connection) states `lib.wiring.connect`'s requirements:
> This function connects interface objects that satisfy the following requirements:
>
> [...]
>
> * For each given path where all members are port members, exactly one member has an `Out` flow.
The actual implementation diverges; the docstring listing these requirements omits the last point, and [notes later …

lib.wiring.connect: diagnostic when no connection made.

---

amaranth/sim/pysim.py

sim.pysim: Only close VCD/GTKW files if we opened them ourselves. [0.4 backport]

---

amaranth/back/rtlil.py

back.rtlil: strip `\` from names added to `name_map`.

---

amaranth/sim/pysim.py

sim.pysim: Only close VCD/GTKW files if we opened them ourselves.

---

amaranth/back/rtlil.py

This was allowed only because Amaranth used it internally. Now that all uses are gone, let's just disallow it entirely.

back.rtlil: Remove code allowing internal yosys cells in `Instance`.

---

amaranth/build/res.py
amaranth/lib/io.py
tests/test_build_res.py
tests/test_lib_io.py

Fixes #1040.
Fixes two unrelated issues:
- when `Subsignal` was involved, the resulting object had plain `Pin` objects instead of flipped
- `i_clk` has wrong direction

lib.io, build.res: Make `Pin` and related objects interfaces.

---

amaranth/hdl/_ast.py
tests/test_hdl_ast.py
tests/test_hdl_rec.py

hdl._ast: Make AST nodes immutable.

---

amaranth/lib/io.py
tests/test_lib_io.py

This prevents duplicate pin names.

lib.io: Make `Pin.name` return the whole path.

---

amaranth/utils.py
tests/test_utils.py

Without this patch, `exact_log2(3)` will print `"{n} is not a power of 2"` instead of `"3 is not a power of 2"` as intended

Some f-strings in utils.py are broken (missing the letter "f")

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

The nested signature is already flipped, which means that its `flatten` method has performed the flipping on member flows already.

lib.wiring: remove unnecessary flipping in `Signature.flatten`

---

amaranth/hdl/_ast.py
amaranth/lib/data.py
amaranth/lib/enum.py
docs/changes.rst
docs/stdlib/data.rst
tests/test_hdl_ast.py
tests/test_lib_data.py
tests/test_lib_enum.py

Implement RFC 51: Add `ShapeCastable.from_bits` and `amaranth.lib.data.Const`.

---

amaranth/hdl/_ir.py
docs/changes.rst
tests/test_hdl_ir.py

hdl._ir: Remove support for non-`Elaboratable` elaboratables.

---

amaranth/sim/core.py

Deprecation warning incorrectly referred to RFC 47 rather than RFC 27.

sim.core: correct deprecation warning

---

amaranth/sim/_base.py
amaranth/sim/_pycoro.py
amaranth/sim/core.py
amaranth/sim/pysim.py
tests/test_sim.py

Before this commit, testbenches (generators added with `add_testbench`) were not only preemptible after any `yield`, but were *guaranteed* to be preempted by another testbench after *every* yield. This is evil: if you have any race condition between testbenches, which is common, this scheduling strategy will maximize the resulting nondeterminism by interleaving your testbench with every other one as much as possible. This behavior is an outcome of the way `add_testbench` is implemented, which is by yielding `Settle()` after every command.
One can observe that:
- `yield value_like` should never preempt;
- `yield assignable.eq()` in `add_process()` should not preempt, since it only sets a `next` signal state, or appends to `write_queue` of a memory state, and never wakes up processes;
- …

Only preempt simulator testbenches on explicit wait points

---

amaranth/sim/_pycoro.py
amaranth/sim/pysim.py
tests/test_sim.py

If delta cycles are expanded (i.e. if the `fs_per_delta` argument to `Simulator.write_vcd` is not zero), then create a string typed variable for each testbench in the simulation, which reflects the current command being executed by that testbench. To make all commands visible, insert a (visual) delta cycle after each executed command, and ensure that there is a change/crossing point in the waveform display each time a command is executed, even if several identical ones in a row.
If delta cycles are not expanded, the behavior is unchanged.
Here is an example of a simulation where two testbenches are racing against each other. In the two screenshots, the testbenches are added in different order.
---
- Depends on https://github.com/amaranth-lang/amaranth/pull/1232

Dump simulation testbench commands as VCD waveforms

---

amaranth/hdl/_ast.py
amaranth/hdl/_repr.py
tests/test_hdl_ast.py
tests/test_lib_data.py
tests/test_lib_enum.py

hdl._ast: fix `_value_repr` computation.

---

amaranth/hdl/_ast.py
amaranth/hdl/_dsl.py
amaranth/hdl/_ir.py
amaranth/sim/core.py
tests/test_hdl_ast.py
tests/test_hdl_dsl.py
tests/test_hdl_ir.py
tests/test_sim.py

Closes #1223
Tested a couple toy designs. The inclusion of FSM names being private should be enough to prevent regressions.
This does remove a bit of diagnostic power from the FSM tests.

Allow Signals to be privately named using `name=""`

---

amaranth/hdl/_ir.py
amaranth/hdl/_xfrm.py
tests/test_hdl_ir.py

Made possible by the new port propagation code freeing up the name.

hdl._ir: rename `Instance.named_ports` to `Instance.ports`.

---

amaranth/back/rtlil.py
amaranth/hdl/_ast.py
amaranth/hdl/_ir.py
amaranth/hdl/_mem.py
amaranth/hdl/_xfrm.py
tests/test_hdl_ast.py

These accessors used to be necessary (in addition to `.shape()`) while the AST nodes were mutable. However, after commit 2bf1b4da that made AST nodes immutable, there is no technical requirement to keep them around. Additionally:
- `len(value)` is shorter than `value.width` and works with any `value`
- `value.shape().signed` is longer than `value.signed` but works with any `value`

Deprecate `{Const,Signal}.{width,signed}` accessors

---

docs/guide.rst

There is no reason to assign names to `IOBufferInstance` submodules because it's ignored anyways.

docs/guide: clarify section on `IOBufferInstance`

---

amaranth/hdl/_ir.py
amaranth/hdl/_xfrm.py
tests/test_hdl_ir.py

hdl._ir: raise an error when an elaboratable is duplicated in hierarchy.

---

amaranth/lib/wiring.py
docs/changes.rst
tests/test_lib_wiring.py

This check was originally added out of abundance of caution, but since then it was observed that reset-less-ness is purely an implementation detail (see #1220), and furthermore it interferes with adaptation of `FIFOInterface` signals (where `[rw]_data` are reset-less) for RFC 61.
Fixes #1220.

lib.wiring: allow reset-less signals in interfaces

---

amaranth/hdl/_ast.py
docs/guide.rst

docs/{guide,reference}: clarify semantics of `a.any()` vs `a.bool()`

---

amaranth/back/rtlil.py
amaranth/hdl/_nir.py
tests/test_back_rtlil.py

back.rtlil: Opportunistically trim zero and sign extension on operands.

---

amaranth/back/rtlil.py
amaranth/back/verilog.py
amaranth/hdl/_ast.py
pyproject.toml
tests/test_back_rtlil.py

This requires a Yosys version from git. The requirement should be bumped to a proper release before Amaranth 0.5.

back.rtlil: implement remaining format specifiers.

---

amaranth/build/res.py

build.res: give a more specific error for `add_clock_constraint(ClockSignal)`

---

amaranth/hdl/__init__.py
amaranth/hdl/_mem.py
amaranth/lib/memory.py
docs/stdlib/memory.rst
tests/test_lib_memory.py

This includes a few minor code changes:
- Removing redundant `lib.memory.Memory.Init = hdl.MemoryData.Init` re-export;
- Renaming `FrozenError` to `FrozenMemory` and moving it to `.hdl`;
- Marking `ReadPort` and `WritePort` as `@final`.

Document RFC 62

---

amaranth/vendor/__init__.py
amaranth/vendor/_siliconblue.py

Devices originally designed by SiliconBlue have one set of primitives, and devices originally designed by AT&T, Alcatel-Lucent, or Lattice have a different set of primitives. This is the first step in merging the non-SiliconBlue Lattice platforms into one.

vendor: LatticeICE40Platform→SiliconBluePlatform.

---

docs/_static/custom.css

docs: remove margin around logo background.

---

amaranth/lib/enum.py
docs/stdlib/enum.rst
tests/test_lib_enum.py

lib.enum: rename `EnumMeta` to `EnumType`.

---

amaranth/hdl/_ast.py
amaranth/lib/enum.py
tests/test_hdl_ast.py
tests/test_lib_enum.py

Turns out that RTLIL enum representation requires such, so add a place to store it.

hdl._ast: add enum name argument to `Format.Enum`.

---

amaranth/sim/_base.py
amaranth/sim/_pyeval.py
amaranth/sim/_pyrtl.py
amaranth/sim/pysim.py
tests/test_sim.py

sim: raise an error when overriding a combinationally-driven signal.

---

.github/workflows/main.yaml
pdm_build.py
pyproject.toml

At the moment this uses a git URL for pdm-backend because required PDM functionality (pdm-project/pdm-backend#217) is not released yet.
Fixes #1229 (hopefully).

pyproject: use `.dev{distance}`, not `+{node}`, for non-release builds

---

amaranth/hdl/__init__.py
amaranth/hdl/_ir.py
amaranth/hdl/_nir.py
tests/test_hdl_ir.py

hdl._nir: add combinational cycle detection.

---

amaranth/hdl/_dsl.py
tests/test_hdl_dsl.py

hdl._dsl: improve error message on `m.domains.cd_foo = ...`.

---

amaranth/hdl/_ast.py
amaranth/hdl/_cd.py
amaranth/hdl/_nir.py
amaranth/lib/io.py
amaranth/sim/core.py
docs/contrib.rst
docs/guide.rst
docs/start.rst
docs/stdlib/wiring.rst

Resolves #1301
The first two commits update the documentation and are simple find-and-replace in python docstrings and rst, respectively.
When rebasing, an additional search may be needed.
The third commit adds additional content and should be reviewed by project maintainers more closely.

Documentation: Changing "combinatorial" to "combinational"

---

README.md
amaranth/vendor/_lattice.py
docs/platform/lattice.rst

This is based on #759, but refactored to use the unified `LatticePlatform` instead of adding a new one.
Validated on LFICL-40-EVN using slightly modified amaranth-lang/amaranth-boards#217

vendor._lattice: add Nexus support.

---

amaranth/vendor/_lattice.py

Use `create_clock` to set clock constraints in .pdc file generated for oxide as per: https://github.com/amaranth-lang/amaranth/pull/759#discussion_r1561582932.

vendor._lattice: Add clock constraints to oxide .pdc template.

---

amaranth/vendor/_lattice.py

Lattice renamed some IO primitives when moving from Diamond to Radiant. This is, naturally, sparsely documented but I found a reference in Table 41 of [^1]. One letter in the name of each primitives is changed, as well as one of the inputs (`i_SCLK` -> `i_CK`). This requires a different IO Buffer specialisation for Nexus (Radiant) compared to MachXO2 and ECP5 which this PR adds.
I don't quite know which name Oxide would expect, but a quick grep among the fuzzing scripts finds the updated name (same as Radiant) and not the previous one. So I assume this change is applicable to Oxide also.
Support for Nexus was recently added in #1342
[^1]: https://www.latticesemi.com/-/media/LatticeSemi/Documents/UserManuals/RZ2/Radiant2_1_migration_guide_diamond.ashx?document_id=52926

vendor._lattice: OFS1P3DX -> OFD1P3DX and IFS1P3DX -> IFD1P3DX for nexus

---

amaranth/lib/io.py
amaranth/vendor/_altera.py
amaranth/vendor/_gowin.py
amaranth/vendor/_lattice.py
amaranth/vendor/_xilinx.py
tests/test_lib_io.py

Also makes `[io]_domain` attributes always 
Having conditionally-present attributes causes more problems than it's worth (see #1347). Just make them contain `None` when irrelevant.
Closes #1347.

vendor.*: fix `[io]_domain` propagation when creating buffers.

---

amaranth/vendor/__init__.py

vendor: add `AMDPlatform` as an alias for `XilinxPlatform`.

---

amaranth/back/rtlil.py
tests/test_back_rtlil.py

This is an unfortunate necessity needed to fix memory inference regressions introduced when we switched to using v2 cells. A better approach, compatible with RFC 54, will need to be figured out for Amaranth 0.6.
Fixes #1011.

back.rtlil: set read port init to all-x.

---

amaranth/vendor/_xilinx.py

This looks like an oversight, when _reset was replaced with _init in FFSynchronizer.

Replace use of _reset with _init in Xilinx platform.

---

amaranth/sim/core.py
amaranth/sim/pysim.py
tests/test_sim.py

Fixes #764.
Things to look at in the review:
* Group names for views and interfaces. The current code uses "view" and "interface". Maybe the name should reference a layout/signature in some way?
* Treating single-field view as in https://github.com/amaranth-lang/amaranth/issues/764#issuecomment-2014220740 is not implemented. It could be implemented by adding a special case.
* I've added tests that check if the code doesn't raise an exception, the resulting gtkw files are not checked. I'm not sure how to best check them; I could compare them with a reference, but this would freeze the signal naming. Is signal naming for views and interfaces specified?
* Had to add another change related to the recent private names commit. Now that there are three separate recursive functions in this PR, …

Emit signal groups in GTKW files

---

amaranth/hdl/_dsl.py
tests/test_hdl_dsl.py

This is semantically ambiguous and breaks the RTLIL emitter.
Fixes #1209.

Forbid empty string as submodule name

---

amaranth/lib/data.py
tests/test_lib_data.py

This is meaningless for a view but meaningful for the underlying value.
Fixes #1375.

Add a diagnostic for slicing `data.View`

---

amaranth/hdl/_ast.py
docs/changes.rst

hdl: remove `Value.implies`.

---

.github/workflows/main.yaml

This has resulted in the 0.5.0 tarball being unintentionally also released as 0.6.0 :(
(The reason we need tags like `0.6.0.dev0` in first place is for SCM version determination to work properly on the `main` branch.)

CI: never upload packages or add releases for `.dev` versions.

---

docs/guide.rst

Minor: perhaps intended initially as "not only with an int but also a value-like object".

docs/guide: remove extraneous "not only".

---

amaranth/lib/data.py
tests/test_lib_data.py

lib.data: make `len()` work on views of array layout.

---

amaranth/lib/data.py
tests/test_lib_data.py

Before this commit, `data.Const` was only comparable to `data.Const` or `data.View`.
After this commit, in addition, it is also comparable to `dict` or `list` provided that such a value is accepted by `layout.const()` where `layout` is the layout of the `data.Const` object.
This change greatly reduces boilerplate in tests by enabling e.g.:
assert (await stream_get(ctx, stream)) == {"value": 1}
instead of:
assert (await stream_get(ctx, stream)) == Const({"value": 1}, stream.p.shape())
Note that, unlike `Layout.const`, which accepts arbitrary `Mapping` or `Sequence` objects, only `dict` and `list` are accepted in comparisons. Also, `data.View` continues to be comparable only to `data.View` and `data.Const`. This is to minimize the scope of the change and reduce likelihood of undesirable …

Make `data.Const` comparable with `list` and `dict` objects compatible with the layout

---

amaranth/lib/data.py
tests/test_lib_data.py

Make `data.Const` comparable with `list` and `dict` objects compatible with the layout [0.5 backport]

---

amaranth/_unused.py
amaranth/_utils.py
amaranth/build/plat.py
amaranth/hdl/_ast.py
amaranth/hdl/_dsl.py
amaranth/hdl/_nir.py
amaranth/lib/cdc.py
amaranth/lib/data.py
amaranth/lib/enum.py
amaranth/lib/wiring.py
amaranth/rpc.py
amaranth/vendor/_xilinx.py
tests/test_back_rtlil.py
tests/test_hdl_ast.py
tests/test_hdl_ir.py
tests/test_lib_enum.py
tests/test_lib_wiring.py

In most cases these two attributes contain the same string, however, in case of nested or locally defined classes, the latter is important for disambiguation.
A few instances of `mod.__name__` remain in the codebase.

Bulk-replace `cls.__name__` with `cls.__qualname__`

---

amaranth/_unused.py
amaranth/_utils.py
amaranth/build/plat.py
amaranth/hdl/_ast.py
amaranth/hdl/_dsl.py
amaranth/hdl/_nir.py
amaranth/lib/cdc.py
amaranth/lib/data.py
amaranth/lib/enum.py
amaranth/lib/wiring.py
amaranth/rpc.py
amaranth/vendor/_xilinx.py
tests/test_back_rtlil.py
tests/test_hdl_ast.py
tests/test_hdl_ir.py
tests/test_lib_enum.py
tests/test_lib_wiring.py

In most cases these two attributes contain the same string, however, in case of nested or locally defined classes, the latter is important for disambiguation.
A few instances of `mod.__name__` remain in the codebase.

Bulk-replace `cls.__name__` with `cls.__qualname__` [0.5 backport]

---

amaranth/lib/io.py
tests/test_lib_io.py

Before this PR, any such port would be displayed as `invert=True`, which is confusing if the original port had no inversion.
`DifferentialPort` is unaffected.

Fix `repr()` of empty `SingleEndedPort`

---

amaranth/lib/enum.py

Before this commit, public names `enum` and `target` were not usable as enumeration member or method names. This was unintentional and our policy is to not reserve public names where they may clash with names defined in downstream code.
This commit makes them a private name (`__enum`, etc). This was chosen instead of a sunder name (`_amaranth_enum_`, etc) because there is a 1:1 correspondence between the attribute and a `ValueCastable` method:
* `shape()` -> `__enum`
* `as_value()` -> `__target`

lib.enum: privatize internal attributes in `EnumView`/`FlagView`

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

This error is very difficult to catch otherwise.
Fixes #1435.

lib.wiring: check type of `m` in `connect(m, ...)`

---

amaranth/lib/wiring.py
tests/test_lib_wiring.py

See https://github.com/amaranth-lang/amaranth/pull/1436.

lib.wiring: check type of `m` in `connect(m, ...)` [0.5 backport]

---

amaranth/lib/data.py
tests/test_lib_data.py

As a side effect, makes iterating over `ArrayLayout` views work.
Fixes #1405.
Fixes #1418.

lib.data: accept negative int and slice for `ArrayLayout` indexing.

---

amaranth/build/plat.py
amaranth/vendor/_gowin.py
amaranth/vendor/_lattice.py
amaranth/vendor/_quicklogic.py
amaranth/vendor/_siliconblue.py
amaranth/vendor/_xilinx.py

build, vendor: use `dir="-"` in `create_missing_domain`.

---

amaranth/lib/stream.py
tests/test_lib_stream.py

Add `payload_init=` argument to `lib.stream.Signature()`

---

amaranth/lib/stream.py
tests/test_lib_stream.py

See https://github.com/amaranth-lang/amaranth/pull/1434.

Add `payload_init=` argument to `lib.stream.Signature()` [0.5 backport]

---

amaranth/hdl/_ast.py
tests/test_hdl_ast.py

We have a warning saying that the init value will be truncated to fit the signal's shape (suppressed for common patterns of 0 and -1), but the introspected via `.init` value is, confusingly, not truncated.

hdl: truncate init value read from `Signal(...).init`

---

amaranth/hdl/_ast.py
tests/test_hdl_ast.py

See https://github.com/amaranth-lang/amaranth/pull/1449.

hdl: truncate init value read from `Signal(...).init` [0.5 backport]

---

amaranth/vendor/_gowin.py

SDC files for Gowin vendor toolchain are normally generated from the IDE.
Example syntax for 'create_clock' can be seen chapter 4.6 of SUG940-1.2E ("SUG940-1.2E_Gowin Design Timing Constraints User Guide.pdf").

vendor._gowin: Fix sdc file syntax.

---

docs/stdlib/data.rst

The RGBLayout class itself is not shapelike, only instances of this class are shape-like. (i.e. `Shape.cast(RGBLayout)` would fail) It's worth being precise especially because in some cases the classes themselves are shape-like, for example in the case of Enums, the classes that inherit from Enum are shape-like.

docs/stdlib/data: improved wording describing example that is shape-like

---

amaranth/hdl/_ast.py
tests/test_sim.py

I noticed an `Enum` could only be used as the last (or sole) component in a format string, otherwise it'd raise:
```
/nix/store/bfp9vca8qrshj749s346ddjc41kj6zxx-python3.12-amaranth-0.5.1/lib/python3.12/site-packages/amaranth/hdl/_ast.py:2542: in __init__
obj = get_field(field_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
field_name = '2'
def get_field(field_name):
nonlocal auto_arg_index
if field_name == "":
if auto_arg_index is None:
raise ValueError("cannot switch from manual field "
"specification to automatic field "
"numbering")
field_name = str(auto_arg_index)
auto_arg_index += 1
elif field_name.isdigit():
if auto_arg_index is not None and auto_arg_index > 0:
raise ValueError("cannot switch from automatic field "
"numbering to manual field " …
```

hdl._ast: name Formatter instance uniquely.

---

docs/guide.rst
docs/stdlib/io.rst
pyproject.toml

This is currently breaking builds because of an invalid escape sequence warning being elevated to error severity.

Bump sphinxcontrib-yowasp-wavedrom dependency

---

amaranth/vendor/_gowin.py
docs/changes.rst

Over at Apicula we're migrating from nextpnr-gowin to nextpnr-himbaechel, and this updates Amaranth to use the new target.
The old target was based on nextpnr-generic and had longstanding problems such as long load times and occasional miscompiles. The new target is implemented as a microarchitecture in nextpnr-himbaechel and is significantly faster, robuster, and already has more features than the old target. Only timing-driven synthesis is still in the works, after which the new target will be pretty much a superset of features.
This PR is slightly breaking in that the end user needs to install the new nextpnr target, but should otherwise be largely compatible. The only change is that if you're passing custom Apicula-specific arguments they need to be changed from `--option value` to …

change gowin platform to use nextpnr-himbaechel

---

amaranth/hdl/_ast.py
amaranth/hdl/_mem.py
tests/test_hdl_mem.py
tests/test_lib_memory.py

hdl.mem: mask initial value to shape.

---

amaranth/build/res.py
docs/changes.rst
tests/test_build_res.py

This makes the only non-deprecated way to do I/O not be a pain when subsignals are involved.
(thanks @meithecatte for the report)

build.res: allow `dir="-"` when requesting resources with subsignals.

---

amaranth/build/res.py
docs/changes.rst
tests/test_build_res.py

This makes the only non-deprecated way to do I/O not be a pain when subsignals are involved.

build.res: allow `dir="-"` when requesting resources with subsignals. [0.5 backport]

---

amaranth/lib/wiring.py

lib.wiring: fix Signature.is_compliant docstring

---

amaranth/hdl/_nir.py
tests/test_hdl_ir.py

Only include the condition of a assignment in the comb edges if the assignment assigns to the bit in question.

hdl._nir: AssignmentList: fix comb_edges_to

---

amaranth/back/rtlil.py
tests/test_back_rtlil.py

back.rtlil: espace { and } in format string

---

amaranth/back/rtlil.py
tests/test_back_rtlil.py

back.rtlil: espace { and } in format string [0.5 backport]

---

amaranth/rpc.py

Do not infer the ports from the publicly accessible wires, but instead delegate finding the ports to the `rtlil.convert` function

rpc: add support for `wiring.Component`

---

amaranth/vendor/_gowin.py

Implement 'add_preferences' override for CST files, allowing customizing physical placement of primitive.
This implementation follows what was done in `vendor._lattice`.

vendor._gowin: Add 'add_preferences' override

---

amaranth/hdl/_dsl.py

This means the `enum_{base_type,value_*}` attributes will be emitted on rtlil export. 
(Also fixes the `src_loc_at`, which used to point at `contextlib`)

hdl._dsl: use `Enum` for fsm state signal

---

amaranth/rpc.py

The ilang alias to the rtlil frontend got removed in https://github.com/YosysHQ/yosys/pull/4704

rpc: use rtlil instead of ilang

---

amaranth/back/cxxrtl.py
amaranth/back/verilog.py
amaranth/vendor/_altera.py
amaranth/vendor/_gowin.py
amaranth/vendor/_lattice.py
amaranth/vendor/_siliconblue.py
tests/utils.py

https://github.com/amaranth-lang/amaranth/pull/1540 did not catch all uses of this command that was deprecated upstream in https://github.com/YosysHQ/yosys/pull/4704

back/vendor: s/ilang/rtlil as a result of YosysHQ/yosys#4704

---

amaranth/back/cxxrtl.py
amaranth/back/verilog.py
amaranth/rpc.py
amaranth/vendor/_altera.py
amaranth/vendor/_gowin.py
amaranth/vendor/_lattice.py
amaranth/vendor/_siliconblue.py
tests/utils.py

backends: :cherries: s/rtlil/ilang (#1540, #1542) to `v0.5.x`

---

amaranth/vendor/_xilinx.py

vendor._xilinx: fix FFSynchronizer with custom shapes.

---

amaranth/build/plat.py

0.5.3
- OS: Windows 11
- PATH includes:  `C:\xilinx\Vivado\2024.2\bin`, `C:\xilinx\Vivado\2024.2\xsct-trim\bin`
run `ArtyA7_35Platform().build(Blinky(), do_build=True, do_program=True)`
```bat
'"E:\repos\bonsai\build/setupEnv.bat"' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'"/setupEnv.bat"' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'"/loader.bat"' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
Traceback (most recent call last):
File "E:\repos\bonsai\bonsai\cli.py", line 63, in <module>
main()
File "E:\repos\bonsai\bonsai\cli.py", line 57, in main
test_arty_a7_35_platform()
File "E:\repos\bonsai\bonsai\cli.py", line 30, in test_arty_a7_35_platform
ArtyA7_35Platform().build(Blinky(), do_build=True, do_program=True)
File …
```

fix: error in invoke_tool when running vivado.bat on Windows

---

amaranth/vendor/_gowin.py

0.6.0.dev76
run `TangNano9kPlatform().build(AnyElaboratableClass(), do_program=True)`
```sh
Warning: Invalid constraint: # (add_preferences placeholder)
1 warning, 0 errors
```
Tracing the cause from the error logs, the problem is probably in the commented out text appended by default in `add_preferences`.
The IO constraints file (.cst) in the gowin platform handles commentouts with `//`, but `add_preferences` handles them with `#`.
I assume that it is probably mistaken for commentout in .ys.
```cst
// Automatically generated by Amaranth 0.6.0.dev76. Do not edit.
IO_LOC “clk27_0__io” 52;
IO_PORT “clk27_0__io” IO_TYPE=LVCMOS33;
(snip)
IO_LOC “button_1__io” 4; ...
IO_PORT “button_1__io” IO_TYPE=LVCMOS33;
IO_LOC “uart_0__tx__io” 17;
IO_PORT “uart_0__tx__io” PULL_MODE=UP;
IO_PORT …
```

vendor._gowin: fix comment syntax for add_preferences

---

amaranth/hdl/_ir.py
tests/test_hdl_ir.py

Improve error raised when returning None from `elaborate`

---

amaranth/vendor/_lattice.py

before this would raise an exception if platform.iter_signal_clock_constraints() returned any constraints.

vendor._lattice: fix typo in clock constraint generation [0.5 backport]

---

amaranth/vendor/_lattice.py

before this would raise an exception if platform.iter_signal_clock_constraints() returned any constraints.

vendor._lattice: fix typo in clock constraint generation

---

.github/workflows/main.yaml
amaranth/back/cxxrtl.py
amaranth/back/verilog.py
amaranth/vendor/_gowin.py
amaranth/vendor/_intel.py
amaranth/vendor/_lattice_ecp5.py
amaranth/vendor/_lattice_ice40.py
docs/install.rst
docs/lang.rst
pyproject.toml
tests/utils.py

Replace all occurrences of `read_ilang` with `read_rtlil`.
Backported from https://github.com/amaranth-lang/amaranth/commit/590cba1d6c00dffba7abb5f399680ac50e252adf into v0.4.x

backends: s/ilang/rtlil as a result of YosysHQ/yosys#4704

---

amaranth/sim/_async.py

Otherwise, when used together with asyncio, the following warning will be printed for each use of `.until()`/`.repeat()`:
E: asyncio: Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<<async_generator_athrow without __name__>()>>
/usr/lib/python3.13/asyncio/base_events.py:744: RuntimeWarning: coroutine method 'aclose' of 'TickTrigger.__aiter__' was never awaited

sim: call `.aclose()` on `TickTrigger` in `.until()` and `.repeat()` [0.5 backport]

---

amaranth/sim/_async.py

Otherwise, when used together with asyncio, the following warning will be printed for each use of `.until()`/`.repeat()`:
E: asyncio: Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<<async_generator_athrow without __name__>()>>
/usr/lib/python3.13/asyncio/base_events.py:744: RuntimeWarning: coroutine method 'aclose' of 'TickTrigger.__aiter__' was never awaited

sim: call `.aclose()` on `TickTrigger` in `.until()` and `.repeat()`

---

amaranth/hdl/_ir.py
tests/test_hdl_ir.py

This PR changes `Fragment.origins` from being overwritten if during `Fragment.get` a `Fragment` is encountered that already has a `Fragment.origins` field to
appending to the preexisting `origins` tuple. This case is interesting for anything using a `FragmentTransformer`. With this change,
```python
from amaranth import *
for transformer in (DomainRenamer("sync"), ResetInserter(Signal()), EnableInserter(Signal())):
origins = Fragment.get(transformer(inst := Module()), None).origins
assert inst in origins
```
no longer asserts, like it does currently.
Some before after examples:
Before:
```python
>>> Fragment.get(DomainRenamer("sync")(Module()), None).origins
(<amaranth.hdl._xfrm.TransformedElaboratable object at 0x7fa86fee1d10>,)
>>> …
```

hdl._ir: chain Fragment.origins with preexisting

---

.github/workflows/main.yaml
amaranth/tracer.py
tests/utils.py

pypy does not have _varname_from_oparg, so fall back to pre cpython-3.11 path 
ref: https://github.com/pypy/pypy/blob/0253c85bf5f86a45760eda7f0af8953ed8a253c7/lib-python/3/dis.py#L351

tracer: fix on pypy-3.11

---

amaranth/lib/cdc.py

Remove reference of out-dated platform method and point to `AsyncFFSynchronizer` instead.
Fix #1605
I kept this in the Platform override section since it seems that this info is only relevant for this part.

Update document for `ResetSynchronizer`
